services:
  postgres:
    image: ""
    container_name: 
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 

    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
