services:
  postgres:
    image: "postgres"
    container_name: traveller_api
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tApi
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tApi

    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
